---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: false
  become: true
  roles:
    - role: prereq
    - role: raspberrypi
    - role: longhorn
    - role: registry

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: agent
  become: true
  roles:
    - role: k3s_agent

