grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.robertbatson.com

  persistence:
    enabled: true
    type: sts
    storageClassName: "longhorn"
    size: 5Gi